### ISSUE TITLE
Small bug in the test for Student attributes

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/orm-mapping-to-table-lab#18]
Hello. I stumbled upon a small bug in the rspec test for Student attributes. Specifically, the test labeled "has an id that is readable but not writable" passes even if I don't have an attr_reader for the "id" attribute (and if I don't have the "id" as an optional argument in #initialize). The test checks to make sure that it can't write to the instance variable "id" after initialization, but it doesn't check to see whether "id" was actually defined.

I have attached a screenshot below. Thank you for looking into this!

Sdcrouse

![image](https://user-images.githubusercontent.com/38870640/49482140-c2f05500-f7e2-11e8-9a71-937e261f4446.png)

**Comment by sgharms** [comment]
@Sdcrouse Interesting find. I suspect it hinges on the fact that `Object` has a method called `.id` that is always truthy. Let me tighten the noose on these tests.

**Comment by sgharms** [comment]
Fixed in #19 .  Thanks

**Comment by Sdcrouse** [comment]
You're welcome! Thanks for fixing that.
