### ISSUE TITLE
Rspec load error

### ISSUE THREAD

**Issue by bacitracin** [learn-co-curriculum/orm-mapping-to-table-lab#6]
Getting this error whenever I run Rspec or Learn commands on Nitrous. Chatted with Seema about it, and ran "Bundle update"but it didn't seem to help. Ran into this issue on the OO Ruby Final Project-Student Scraper, this lab, and the ORM Mapping Database Rows to Objects Lab-- basically the last three labs I've tried. I went back to old labs, ran Learn and didn't run into the same issues. They were fine.  I haven't changed any of the spec files. 

Here's the error: 
➜  orm-mapping-to-table-lab-v-000 git:(master) ✗ learn
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rspec/expectations (Load
Error)
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in`require'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:640:in `block in expect_with'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:635:in`map'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:635:in `expect_with'
        from /home/nitrous/code/labs/orm-mapping-to-table-lab-v-000/spec/spec_helper.rb:9:in`block in <top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core.rb:97:in `configure'
        from /home/nitrous/code/labs/orm-mapping-to-table-lab-v-000/spec/spec_helper.rb:5:in`<top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in`require'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `block in requires='
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in`each'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/ from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:108:in `each'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:108:in`process_options_into'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:21:in `configure'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:101:in`setup'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in`run'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/exe/rspec:4:in`<top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/rspec:23:in `load'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/rspec:23:in`<main>'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/ruby_executable_hooks:15:in`<main>'2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `requires='
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:109:in`block in process_options
_into'

**Comment by AnnJohn** [comment]
Sorry @bacitracin for the issues that you're having.

@kvignali can you look into this issue for this student? Thanks!

**Comment by bacitracin** [comment]
The issue for this lab, along with orm-mapping-db-to-ruby-object-lab-v-000 was solved by manually typing in "gem install sqlite3" in the Nitrous terminal. Still having issues with the Student Scraper, so I'll raise an issue there.
