### ISSUE TITLE
my lab does not run learn or rspec

### ISSUE THREAD

**Issue by imkaruna** [learn-co-curriculum/orm-mapping-to-table-lab#9]
## ERROR from running learn 

 orm-mapping-to-table-lab-v-000 git:(master) learn
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- sqlite3 (LoadError)
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in`require'
        from /home/nitrous/code/labs/orm-mapping-to-table-lab-v-000/config/environment.rb:1:in `<top (required)>'
        from /home/nitrous/code/labs/orm-mapping-to-table-lab-v-000/lib/student.rb:2:in`require_relative'
        from /home/nitrous/code/labs/orm-mapping-to-table-lab-v-000/lib/student.rb:2:in `<top (required)>'
        from /home/nitrous/code/labs/orm-mapping-to-table-lab-v-000/spec/spec_helper.rb:2:in`require_relative'
        from /home/nitrous/code/labs/orm-mapping-to-table-lab-v-000/spec/spec_helper.rb:2:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in`require'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in`block in requires='
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `each'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in`requires='
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:108:in`each'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:21:in`configure'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:101:in `setup'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in`run'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in`invoke'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/exe/rspec:4:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/rspec:23:in`load'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/rspec:23:in `<main>'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/ruby_executable_hooks:15:in`eval'
#         from /usr/local/opt/rbenv/versions/2.1.5/bin/ruby_executable_hooks:15:in `<main>'
## ERROR from running rspec

➜  orm-mapping-to-table-lab-v-000 git:(master) rspec
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- sqlite3 (LoadError)
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in`require'
        from /home/nitrous/code/labs/orm-mapping-to-table-lab-v-000/config/environment.rb:1:in `<top (required)>'
        from /home/nitrous/code/labs/orm-mapping-to-table-lab-v-000/lib/student.rb:2:in`require_relative'
        from /home/nitrous/code/labs/orm-mapping-to-table-lab-v-000/lib/student.rb:2:in `<top (required)>'
        from /home/nitrous/code/labs/orm-mapping-to-table-lab-v-000/spec/spec_helper.rb:2:in`require_relative'
        from /home/nitrous/code/labs/orm-mapping-to-table-lab-v-000/spec/spec_helper.rb:2:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in`require'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in`block in requires='
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `each'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in`requires='
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:108:in`each'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:21:in`configure'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:101:in `setup'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in`run'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in`invoke'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.1/exe/rspec:4:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/rspec:23:in`load'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/rspec:23:in `<main>'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/ruby_executable_hooks:15:in`eval'
        from /usr/local/opt/rbenv/versions/2.1.5/bin/ruby_executable_hooks:15:in `<main>'

**Comment by aviflombaum** [comment]
Fixing this and lots of other issues with this lab

**Comment by aviflombaum** [comment]
Everything should be fixed now.
